### ISSUE TITLE
config in YML format

### ISSUE THREAD

**Issue by stefanocudini** [pelias/config#134]
good idea considering the size of config in pelias.json file!
I think that can be simply refact

**Comment by missinglink** [comment]
Hi @stefanocudini I don't understand what problem would be solved from converting the format from JSON to YAML?

You mentioned "considering the size of config in pelias.json file!"

Is your aim to reduce the file size? my local file is `2.7KB`.
What would be the advantage of reducing the file size further?

**Comment by orangejulius** [comment]
Hi @stefanocudini,
No, sorry, we definitely are not going to add `YAML` support :)

While comments are nice, otherwise YAML is a bit of a pain (in my opinion at least, having done quite a bit with Kubernetes). Even if it was a far superior format, this is one of those things that does in theory sound like a nice feature, but would add a large and lasting support burden.

**Comment by stefanocudini** [comment]
> While comments are nice

yes I thought exactly about the comments, and the fact that the yml format is more human redable for large configurations
