### ISSUE TITLE
Invalid apiVersion "1.7"

### ISSUE THREAD

**Issue by missinglink** [pelias/config#15]
it appears that newer versions use "1.x" instead of "1.7".

version number [here](https://github.com/pelias/config/blob/master/config/defaults.json#L3) needs to be changed and published.

```bash
    x TypeError: Invalid apiVersion "1.7", expected a function or one of master, 1.x, 1.3, 1.2, 1.1, 1.0, 0.90
    x TypeError: Invalid apiVersion "1.7", expected a function or one of master, 1.x, 1.3, 1.2, 1.1, 1.0, 0.90
```

**Comment by orangejulius** [comment]
I believe we've resolved this issue, since all pelias repos now require a new enough version of the Elasticsearch node module that 1.7 is defined as an API version. If anyone is still running into this issue, please re-open and paste the output of `npm ls` and `git show` for the repository giving you trouble.
