### ISSUE TITLE
I wished it was easier to set hostname of ES...

### ISSUE THREAD

**Issue by rjpereira** [pelias/config#53]
I can't really find an easy solution to my scenario. I'm planning on using Pelias with an external Elastic Search instance provisioned by AWS, and pelias running from a docker instance. Normally this would be as easy as setting the hostname as a environment variable. But with current config the hostname is only defined in a json which doesn't leave many options out:
- pointing to a different .json file at run time: not useful on scenarios where you have ES being provisioned automatically by Cloudformation and you don't have the hostname upon deployment
- using add-host with a fixed name not friendly since requires an IP rather than an host name.
- only solution seems to be patching the json at run time replacing some "tag" string.

My proposed solution would be to have the configuration have a search sequence from .json first, and environment variables second, to allow this configuration in those scenarios. Any thoughts for or against ?

**Comment by missinglink** [comment]
@rjpereira in production we have static DNS addresses for our AWS load balancers in each environment, then those DNS names are stored in a per-stack `pelias.json` file which is loaded via env var as per https://github.com/pelias/config#production-settings

**Comment by missinglink** [comment]
I would prefer not to change the existing implementation of `pelias/config` to one that supported fallback scenarios as that would add complexity that IMHO could be better handled by the system administrator via scripts.

**Comment by missinglink** [comment]
I'm not sure I fully understand, so if I'm way off, let me know.

From what I gather you have an environment with hard dependencies between your service layer and your application layer, presumably the services will have to expose their location to the application somehow.

Am I correct in saying that the issue is converting that service discovery info in to JSON format?

**Comment by orangejulius** [comment]
Hello from over a year in the future.

Since this issue was first opened Pelias has moved towards having many services, so the question of how to configure them has only grown in importance. However I agree with missinglink that we don't intend to support ENV vars for configuring the hosts. We like `pelias.json`. Without it, there would be far too many ENV vars to configure.

Instead, here are some suggestions. that might be useful by themselves or in combination:
* Use DNS to provide consistent hostnames for Pelias to use across services
* Use a load balancer so that needing to change the hostname happens less often
* Use some mechanism to update `pelias.json` and restart any API instances when it changes. This is useful anyways for pushing config changes

For geocode.earth we use that last system, using the Kubernetes [ConfigMap](https://github.com/pelias/kubernetes/blob/master/templates/configmap.tpl) feature, and tell Kubernetes to [re-create](https://github.com/pelias/kubernetes/blob/master/templates/api-deployment.tpl#L17) our API containers whenever the config changes.

If anyone is stuck figuring out a good way to handle this, let us know, we can probably help.

**Comment by MALKARAJ** [comment]
how to configure our own elasticsearch instead of elasticsearch image?
